name: Unit tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies with clean install
      run: npm ci
    - name: Compile
      run: npm run compile
    - name: Run tests
      run: npm run devmatch-test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results.json
